<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.29" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TeaQL.Core\TeaQL.Core.csproj" />
    <ProjectReference Include="..\..\src\TeaQL.Provider.PostgreSql\TeaQL.Provider.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\TeaQL.Sql\TeaQL.Sql.csproj" />
    <ProjectReference Include="..\..\src\TeaQL.TfpEndpoint\TeaQL.TfpEndpoint.csproj" />
    <ProjectReference Include="..\..\src\TeaQL.Provider.Sqlite\TeaQL.Provider.Sqlite.csproj" />
  </ItemGroup>

</Project>
