<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeaQL.Runtime\TeaQL.Runtime.csproj" />
    <ProjectReference Include="..\TeaQL.DataService\TeaQL.DataService.csproj" />
    <ProjectReference Include="..\TeaQL.Core\TeaQL.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
